[project]
name = "credit-risk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "catboost>=1.2.10",
    "imblearn>=0.0",
    "ipykernel>=7.3.0",
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "streamlit>=1.63.0",
    "xgboost>=3.4.1",
]
